### ISSUE TITLE
one question for the default value of field prefix

### ISSUE THREAD

**Issue by max190113** [rte-france/SCL_Loader#29]
I am a student who has just come into contact with 61850. If the prefix field is not used, must it be a space " ", and why can't it be ""?
Because I saw some SCL files where the prefix does not have a space.
Anyone could help me? thanks

**Comment by vermeulenthi** [comment]
Hi @max190113, Indeed, there is a difference between the XSD used in the SCL_Loader et those provided by 61850-6 on tPrefix type and prefix default values. 
A fix is being prepared. Thanks
